// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBEKGCdfCQ9Fp_wLVCEB4-qqDGzQyoXk',
    appId: '1:832782786362:web:7a418ba8ecb92ad419ba03',
    messagingSenderId: '832782786362',
    projectId: 'coupona-6b050',
    authDomain: 'coupona-6b050.firebaseapp.com',
    storageBucket: 'coupona-6b050.appspot.com',
    measurementId: 'G-HCLPTBM92B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYVYBAf2qVJJ62uGnm2jMk54HIT3n30w',
    appId: '1:832782786362:android:a83d2a15865fe6eb19ba03',
    messagingSenderId: '832782786362',
    projectId: 'coupona-6b050',
    storageBucket: 'coupona-6b050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdSQ4dgvpLvzRVfUpO-D3DhcL-MKzpcw',
    appId: '1:832782786362:ios:267ae1142712cb7119ba03',
    messagingSenderId: '832782786362',
    projectId: 'coupona-6b050',
    storageBucket: 'coupona-6b050.appspot.com',
    iosClientId: '832782786362-jig6dkklkbt4hjo4pmjkod0kqaljdj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.couponaMerchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkdSQ4dgvpLvzRVfUpO-D3DhcL-MKzpcw',
    appId: '1:832782786362:ios:267ae1142712cb7119ba03',
    messagingSenderId: '832782786362',
    projectId: 'coupona-6b050',
    storageBucket: 'coupona-6b050.appspot.com',
    iosClientId: '832782786362-jig6dkklkbt4hjo4pmjkod0kqaljdj4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.couponaMerchant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqBEKGCdfCQ9Fp_wLVCEB4-qqDGzQyoXk',
    appId: '1:832782786362:web:6256cf97d7d3830a19ba03',
    messagingSenderId: '832782786362',
    projectId: 'coupona-6b050',
    authDomain: 'coupona-6b050.firebaseapp.com',
    storageBucket: 'coupona-6b050.appspot.com',
    measurementId: 'G-R37321HFZ8',
  );
}
